---
title: Колір та розмір обведення
hero_image: images/banner.png
description: Колір та розмір обведення
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Колір та розмір обведення
