---
title: Kleur en dikte van de randen
hero_image: images/banner.png
description: Kleur en dikte van de randen
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Kleur en dikte van de randen
