title: processing-stroke
hero_image: images/banner.png
description: processing-stroke description
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
