---
title: Colour and weight of borders
hero_image: images/banner.png
description: Colour and weight of borders
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Colour and weight of borders
