---
title: Color y grosor de los bordes
hero_image: images/banner.png
description: Color y grosor de los bordes
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Color y grosor de los bordes
