---
title: Farbe und Stärke der Ränder
hero_image: images/banner.png
description: Farbe und Stärke der Ränder
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - title: Farbe und Stärke der Ränder
