---
title: Cor e peso das bordas
hero_image: images/banner.png
description: Cor e peso das bordas
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Cor e peso das bordas
