---
title: Kolor i grubość obramowań
hero_image: images/banner.png
description: Kolor i grubość obramowań
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Kolor i grubość obramowań
