---
title: Couleur et épaisseur des bordures
hero_image: images/banner.png
description: Couleur et épaisseur des bordures
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Couleur et épaisseur des bordures
