---
title: Colore e spessore dei bordi
hero_image: images/banner.png
description: Colore e spessore dei bordi
version: 4
listed: false
copyedit: false
last_tested: "2021-08-10"
steps:
  - 
    title: Colore e spessore dei bordi
